var holarchy =  
	{"id": 1,	"parentid": 0,	"name": "S1",	"size": 500,	"type": "S",	"children": [
		{"id": "F32", "parentid": 1, "name": "F32", "size": 200, 	"type": "F" ,	"children": [
				{"id": "L39", "parentid": 1, "name": "L39", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L40", "parentid": 1, "name": "L40", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L41", "parentid": 1, "name": "L41", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L42", "parentid": 1, "name": "L42", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]}
		  ]},
		{"id": "F35", "parentid": 1, "name": "F35", "size": 200, 	"type": "F" ,	"children": [
				{"id": "L39", "parentid": 1, "name": "L39", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L40", "parentid": 1, "name": "L40", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]}
		  ]},
		{"id": "F33", "parentid": 1, "name": "F33", "size": 200, 	"type": "F" ,	"children": [
				{"id": "L76", "parentid": 1, "name": "L76", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L77", "parentid": 1, "name": "L77", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L78", "parentid": 1, "name": "L78", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L75", "parentid": 1, "name": "L75", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]}
		  ]},
		{"id": "F37", "parentid": 1, "name": "F37", "size": 200, 	"type": "F" ,	"children": [
				{"id": "L99", "parentid": 1, "name": "L99",  "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L100", "parentid": 1, "name": "L100", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L101", "parentid": 1, "name": "L101", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L102", "parentid": 1, "name": "L102", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L103", "parentid": 1, "name": "L103", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L104", "parentid": 1, "name": "L104", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]}
		  ]},
		{"id": "F38", "parentid": 1, "name": "F38", "size": 200, 	"type": "F" ,	"children": [
				{"id": "L135", "parentid": 1, "name": "L135", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L136", "parentid": 1, "name": "L136", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]}
		  ]},
		{"id": "F29", "parentid": 1, "name": "F29", "size": 200, 	"type": "F" ,	"children": [
				{"id": "L147", "parentid": 1, "name": "L147", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L148", "parentid": 1, "name": "L148", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L149", "parentid": 1, "name": "L149", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L150", "parentid": 1, "name": "L150", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]}
		  ]},
		{"id": "F31", "parentid": 1, "name": "F31", "size": 200, 	"type": "F" ,	"children": [
				{"id": "L171", "parentid": 1, "name": "L171", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]}
		]},
		{"id": "F27",  "parentid": 1, "name": "F27" , "size": 200, 	"type": "F" ,	"children": [
				{"id": "L177", "parentid": 1, "name": "L177", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L178", "parentid": 1, "name": "L178", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L179", "parentid": 1, "name": "L179", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L180", "parentid": 1, "name": "L180", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]}
		  ]},
		{"id": "F28", "parentid": 1, "name": "F28", "size": 200, 	"type": "F" ,	"children": [
				{"id": "L201", "parentid": 1, "name": "L201", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L202", "parentid": 1, "name": "L202", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L203", "parentid": 1, "name": "L203", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L204", "parentid": 1, "name": "L204", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]}
		  ]},
		{"id":  "F9", "parentid": 1, "name": "F9 ", "size": 200, 	"type": "F" ,	"children": [
				{"id": "L225", "parentid": 1, "name": "L225", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L226", "parentid": 1, "name": "L226", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]}
		  ]},
		{"id":  "F7", "parentid": 1, "name": "F7 ", "size": 200, 	"type": "F" ,	"children": [
				{"id": "L237", "parentid": 1, "name": "L237", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L238", "parentid": 1, "name": "L238", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]}
		  ]},
		{"id":  "F8", "parentid": 1, "name": "F8 ", "size": 200, 	"type": "F" ,	"children": [
				{"id": "L249", "parentid": 1, "name": "L249", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L250", "parentid": 1, "name": "L250", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]}
		  ]},
		{"id":  "F6", "parentid": 1, "name": "F6 ", "size": 200, 	"type": "F" ,	"children": [
				{"id": "L261", "parentid": 1, "name": "L261", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L262", "parentid": 1, "name": "L262", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]}
		  ]},
		{"id": "F10", "parentid": 1, "name": "F10", "size": 200, 	"type": "F",	"children": [
				{"id": "L273", "parentid": 1, "name": "L273", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L274", "parentid": 1, "name": "L274", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L275", "parentid": 1, "name": "L275", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L276", "parentid": 1, "name": "L276", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]}
		  ]},
		{"id": "F24", "parentid": 1, "name": "F24", "size": 200, 	"type": "F" ,	"children": [
				{"id": "L297", "parentid": 1, "name": "L297", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L298", "parentid": 1, "name": "L298", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L299", "parentid": 1, "name": "L299", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L300", "parentid": 1, "name": "L300", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]}
		  ]},
		{"id": "F13", "parentid": 1, "name": "F13", "size": 200, 	"type": "F" ,	"children": [
				{"id": "L321", "parentid": 1, "name": "L321", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L322", "parentid": 1, "name": "L322", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]}
		  ]},
		{"id": "F14", "parentid": 1, "name": "F14", "size": 200, 	"type": "F" ,	"children": [
				{"id": "L333", "parentid": 1, "name": "L333", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L334", "parentid": 1, "name": "L334", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L335", "parentid": 1, "name": "L335", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L336", "parentid": 1, "name": "L336", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]}
		  ]},
		{"id": "F15", "parentid": 1, "name": "F15", "size": 200, 	"type": "F" ,	"children": [
				{"id": "L357", "parentid": 1, "name": "L357", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L358", "parentid": 1, "name": "L358", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]}
		  ]},
		{"id": "F17", "parentid": 1, "name": "F17", "size": 200, 	"type": "F" ,	"children": [
				{"id": "L369", "parentid": 1, "name": "L369", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L370", "parentid": 1, "name": "L370", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L371", "parentid": 1, "name": "L371", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L372", "parentid": 1, "name": "L372", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]}
		  ]},
		{"id": "F18", "parentid": 1, "name": "F18", "size": 200, 	"type": "F" ,	"children": [
				{"id": "L393", "parentid": 1, "name": "L393", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L394", "parentid": 1, "name": "L394", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]}
		  ]},
		{"id": "F19", "parentid": 1, "name": "F19", "size": 200, 	"type": "F"  ,	"children": [
				{"id": "L405", "parentid": 1, "name": "L405", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L406", "parentid": 1, "name": "L406", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L407", "parentid": 1, "name": "L407", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L408", "parentid": 1, "name": "L408", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L409", "parentid": 1, "name": "L409", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L410", "parentid": 1, "name": "L410", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]}
		  ]},
		{"id": "F22", "parentid": 1, "name": "F22", "size": 200, 	"type": "F" ,	"children": [
		
				{"id": "L441", "parentid": 1, "name": "L441", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L442", "parentid": 1, "name": "L442", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L443", "parentid": 1, "name": "L443", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L444", "parentid": 1, "name": "L444", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]}
		  ]},
		{"id": "F23", "parentid": 1, "name": "F23", "size": 200, 	"type": "F"  ,	"children": [
				{"id": "L465", "parentid": 1, "name": "L465", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L466", "parentid": 1, "name": "L466", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]}
		  ]},
		{"id": "F20", "parentid": 1, "name": "F20", "size": 200, 	"type": "F"  ,	"children": [
				{"id": "L477", "parentid": 1, "name": "L477", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L478", "parentid": 1, "name": "L478", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L479", "parentid": 1, "name": "L479", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L480", "parentid": 1, "name": "L480", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L481", "parentid": 1, "name": "L481", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]}
		  ]},
		{"id":  "F3", "parentid": 1, "name": "F3 ", "size": 200, 	"type": "F" ,	"children": [
				{"id": "L507", "parentid": 1, "name": "L507", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L508", "parentid": 1, "name": "L508", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L509", "parentid": 1, "name": "L509", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L510", "parentid": 1, "name": "L510", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]}
		  ]},
		{"id": "F25", "parentid": 1, "name": "F25", "size": 200, 	"type": "F"  ,	"children": [
				{"id": "L531", "parentid": 1, "name": "L531", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L532", "parentid": 1, "name": "L532", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L533", "parentid": 1, "name": "L533", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]},
				{"id": "L534", "parentid": 1, "name": "L534", "size": 100, 	"type": "L",	"children": [	{"id": "H1", "parentid": 1, "name": "H1", "size": 100, 	"type": "H"},	{"id": "H2", "parentid": 1, "name": "H2", "size": 100, 	"type": "H"},	{"id": "H3", "parentid": 1, "name": "H3", "size": 100, 	"type": "H"},		{"id": "H4", "parentid": 1, "name": "H4", "size": 100, 	"type": "H"}	  ]}
		  ]}
	]};
 